/* Generated By:JavaCC: Do not edit this line. LC3ParserConstants.java */
package nju.edu.lc3.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface LC3ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int JMP = 7;
  /** RegularExpression Id. */
  int JSR = 8;
  /** RegularExpression Id. */
  int JSRR = 9;
  /** RegularExpression Id. */
  int LD = 10;
  /** RegularExpression Id. */
  int LDI = 11;
  /** RegularExpression Id. */
  int LDR = 12;
  /** RegularExpression Id. */
  int LEA = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int RET = 15;
  /** RegularExpression Id. */
  int RTI = 16;
  /** RegularExpression Id. */
  int ST = 17;
  /** RegularExpression Id. */
  int STI = 18;
  /** RegularExpression Id. */
  int STR = 19;
  /** RegularExpression Id. */
  int TRAP = 20;
  /** RegularExpression Id. */
  int BR = 21;
  /** RegularExpression Id. */
  int ORIG = 22;
  /** RegularExpression Id. */
  int END = 23;
  /** RegularExpression Id. */
  int FILL = 24;
  /** RegularExpression Id. */
  int STRINGZ = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int REGISTER = 27;
  /** RegularExpression Id. */
  int NUMBER = 28;
  /** RegularExpression Id. */
  int DECIMAL = 29;
  /** RegularExpression Id. */
  int HEX = 30;
  /** RegularExpression Id. */
  int OCTAL = 31;
  /** RegularExpression Id. */
  int STRING = 32;
  /** RegularExpression Id. */
  int ID = 33;
  /** RegularExpression Id. */
  int COMMENT = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"ADD\"",
    "\"AND\"",
    "\"JMP\"",
    "\"JSR\"",
    "\"JSRR\"",
    "\"LD\"",
    "\"LDI\"",
    "\"LDR\"",
    "\"LEA\"",
    "\"NOT\"",
    "\"RET\"",
    "\"RTI\"",
    "\"ST\"",
    "\"STI\"",
    "\"STR\"",
    "\"TRAP\"",
    "<BR>",
    "\".ORIG\"",
    "\".END\"",
    "\".FILL\"",
    "\".STRINGZ\"",
    "\",\"",
    "<REGISTER>",
    "<NUMBER>",
    "<DECIMAL>",
    "<HEX>",
    "<OCTAL>",
    "<STRING>",
    "<ID>",
    "<COMMENT>",
  };

}
